name: btools
channels:
  - conda-forge
dependencies:
  - xarray
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - scikit-learn
  - scipy
  - dask
  - cartopy
  - xeofs
  - shapely
  - rioxarray
  - gdal
  - pyproj
  - ecmwf-api-client
  - eccodes
  - cfgrib
  - pygrib
  - metview-batch
  - netcdf4
  - ipykernel
